spring:
  profiles:
    active: dev  # Cambia a "prod" en despliegue o usa una variable de entorno

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%thread]){magenta} %clr(%logger{36}){cyan} : %msg%n%wEx"
