spring:
  datasource:
    url: jdbc:postgresql://ep-floral-base-a4bfswc8-pooler.us-east-1.aws.neon.tech/neondb
    username: neondb_owner
    password: npg_G0iDZ7HTreIb
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.playtodoo: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%t]){magenta} %clr(%-40.40logger{39}){cyan} : %m%n%wEx"
