name: CI/CD Pipeline - Playtodoo

on:
  push:
    branches:
      - main

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build, Test & Verify Coverage (80% Minimum)
        run: mvn clean verify

      - name: Upload JaCoCo Report (Optional - for GitHub Pages)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

  deploy:
    needs: build-test-coverage
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Trigger Coolify Deployment
        run: |
          curl -X POST "http://31.97.12.29:8000/api/v1/deploy?uuid=ecwc0sgs0g8wkws8owgkswcg&force=false" \
          -H "Authorization: Bearer ${{ secrets.COOLIFY_DEPLOY_TOKEN }}"