name: Deploy to Coolify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deployment
        run: |
          curl -X POST "http://31.97.12.29:8000/api/v1/deploy?uuid=ecwc0sgs0g8wkws8owgkswcg&force=false" \
          -H "Authorization: Bearer ${{ secrets.COOLIFY_DEPLOY_TOKEN }}"
